export const errors = {
  GET_ERROR: 'GET_ERRORS',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export const projects = {
  GET_PROJECTS: 'GET_PROJECTS',
  GET_PROJECT: 'GET_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
};

export const backlog = {
  GET_BACKLOG: 'GET_BACKLOG',
  GET_PROJECT_TASK: 'GET_PROJECT_TASK',
  DELETE_PROJECT_TASK: 'DELETE_PROJECT_TASK',
};
